/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/assessments/$id'
    | '/assessments/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/assessments/$id'
    | '/assessments/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/assessments/$id'
    | '/assessments/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  AssessmentsIdRoute: AssessmentsIdRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
